# SWEDISH _____________________________
  [Languages.sv]
    lang = "Svenska"
    LanguageCode = "sv"
    title = "Litecoin - Öppen källkod P2P digitalvaluta"
    weight = 21

  # Hero section
  [Languages.sv.hero]
    # title = "The Cryptocurrency For Payments"
    # subtitle = "Based on Blockchain Technology"
   otherversions = "Andra versioner"
   buylitecoin = "Köp Litecoin"

  # Navigation
  [Languages.sv.navigation]
    brand = "litecoin"
    download = "LADDA NER"
    about = "About"
    team = "Team"
    contact = "Contact"

    # postpended links
    [[Languages.sv.menu.postpend]]
      url = "https://litecointalk.io/"
      name = "Forum"
      weight = 10

    [[Languages.sv.menu.postpend]]
      url = "https://litecoin.net"
      name = "Foundation"
      weight = 10

  # About section
  [Languages.sv.about]
    enable = true
    title = "Vad är Litecoin?"
    subtitle = "Litecoin is a peer-to-peer Internet currency that enables instant, near-zero cost payments to anyone in the world. Litecoin is an open source, global payment network that is fully decentralized without any central authorities. Mathematics secures the network and empowers individuals to control their own finances. Litecoin features faster transaction confirmation times and improved storage efficiency than the leading math-based currency. With substantial industry support, trade volume and liquidity, Litecoin is a proven medium of commerce complementary to Bitcoin."

    [[Languages.sv.about.row]]
      [[Languages.sv.about.row.list]]
        icon = "fa-group"
        title = "Gemenskap"
        description =  '<p class="text-no-margin text-left text-muted">Find support across a growing number of Litecoin communities:</p><ul class="text-muted text-left "> <li><a href="https://litecointalk.io">Litecoin Forums</a></li> <li><a href="http://www.reddit.com/r/litecoin">Reddit Litecoin</a></li> <li><a href="https://twitter.com/search?q=litecoin%20-bitcoin&amp;src=typd">Search for Users on Twitter</a></li> <li><a href="http://freenode.net/" rel="nofollow">IRC FreeNode</a> network channels <a href="http://webchat.freenode.net/?channels=litecoin" rel="nofollow">#litecoin</a> (for general users) and <a href="http://webchat.freenode.net/?channels=litecoin-dev" rel="nofollow">#litecoin-dev</a> (for developers).</li> </ul>'

      [[Languages.sv.about.row.list]]
        icon = "fa-laptop"
        title = "Resurser"
        description = 'Hitta allmän information samt en lista över tjänster och börser som stödjer Litecoin på <a href="http://litecoin.info">Litecoin Wiki</a>. <br> Up-to-date nätverksstatistik finns på <a href="https://chainz.cryptoid.info/ltc/"> Litecoin Block Explorer Charts</a>. <br> Källkod för Litecoin Core och relaterade projekt finns på <a href="https://github.com/litecoin-project"> GitHub </a>.'

      [[Languages.sv.about.row.list]]
        icon = "fa-heart"
        title = "Öppen källkodsmjukvara"
        description = "Litecoin är ett öppet källkod-projekt släppt under MIT/X11-licens vilket ger dig möjlighet att köra, ändra, kopiera och sprida programvaran och om du så vill, modifierade kopior av programvaran. Programmet släpps i en öppen process som gör det möjligt för oberoende kontroll av binärfiler och deras motsvarande källkod."

    [[Languages.sv.about.row]]
      [[Languages.sv.about.row.list]]
        icon = "fa-link"
        title = "Blockkedja"
        description = "Litecoin blockedjan kan hantera högre transaktionsvolymer än dess motsvarighet - Bitcoin. På grund av tätare block generering, stödjer nätverket fler transaktioner utan att behöva ändra programvaran i framtiden. <br />Som ett resultat får försäljare snabbare bekräftelser och har samtidigt förmågan att vänta på fler bekräftelser när de säljer större objekt."

      [[Languages.sv.about.row.list]]
        icon = "fa-lock"
        title = "Plånbokskryptering"
        description = "Plånbokskryptering gör att du kan säkra din plånbok, så att du kan granska transaktioner och ditt saldo men måste ange ditt lösenord innan du kan spendera litecoins. <br />Detta ger skydd mot virus och trojaner som försöker stjäla din plånbok samt en sundhetskontroll före sändning av betalningar."

      [[Languages.sv.about.row.list]]
        icon = "fa-money"
        title = "Mining Reward"
        description = "Miners belönas för närvarande med 6.25 nya litecoins per block, ett belopp som halveras ungefär var fjärde år (var 840.000 block). <br />Litecoinnätverket är därför planerad att producera 84 miljoner litecoins, vilket är fyra gånger fler än Bitcoins."

  # download section
  [Languages.sv.download]
    enable = true
    gpg = "GPG Signatures"
    download = "LADDA NER"
    source = "KÄLLA"
    releasenotes = "Släppnotiser"
    upgradenotes = "Uppgraderingsnotiser"

    windows = "för Windows"
    mac = "för Mac OS X"
    linux = "för Linux"
    android = "Litewallet för Android"
    electrum = "Electrum Litecoin"

  # Contact section
  [Languages.sv.contact]
    enable = true
    # title = "Contact us"
    subtitle  = 'Du kan kontakta Litecoinprojektets utvecklingsteam på <a href="mailto:contact@litecoin.org">contact@litecoin.org</a>'

  # Footer section
  [Languages.sv.footer]
    enable = true
    copyright = 'Copyright &copy; 2011-2023 Litecoin Project. Alla rättigheter reserverade.'
