# TURKISH _____________________________
  [Languages.tr]
    lang = "Türkçe"
    LanguageCode = "tr"
    title = "Litecoin - Açık kaynaklı P2P dijital para birimi"
    weight = 22

  # Hero section
  [Languages.tr.hero]
   title = "Ödemeler İçin Kripto Para"
   subtitle = "Blockchain Teknolojisine Dayalı"
   otherversions = "Diğer sürümler"
   buylitecoin = "Litecoin satın alın"

  # Navigation
  [Languages.tr.navigation]
    brand = "litecoin"
    download = "İndir"
    about = "Hakkında"
    team = "Ekip"
    contact = "İletişim"

    # postpended links
    [[Languages.tr.menu.postpend]]
      url = "https://litecointalk.io/"
      name = "Forum"
      weight = 10

    [[Languages.tr.menu.postpend]]
      url = "https://litecoin.net"
      name = "Kuruluş"
      weight = 10

  # About section
  [Languages.tr.about]
    enable = true
    title = "Litecoin nedir?"
    subtitle = "Litecoin, dünyadaki herhangi birine anında, sıfıra yakın maliyetli ödeme sağlayan eşler arası bir internet para birimidir. Litecoin tamamen merkezi olmayan, açık kaynaklı bir küresel ödeme ağıdır. Matematik ağı korur ve bireylere kendi mali kaynaklarını kontrol etmelerini sağlar. Litecoin, önde gelen matematik temelli para birimlerine göre daha hızlı işlem onay süreleri ve gelişmiş depolama verimliliği sunar. Önemli endüstri desteği, ticaret hacmi ve likidite ile Litecoin, Bitcoin'i tamamlayan kanıtlanmış bir ticaret ortamıdır."

    [[Languages.tr.about.row]]
      [[Languages.tr.about.row.list]]
        icon = "fa-group"
        title = "Topluluk"
        description =  '<p class="text-no-margin text-left text-muted">Sayısı her geçen gün artan Litecoin topluluklarından destek alabilirsiniz: </p><ul class="text-muted text-left "> <li><a href="https://litecointalk.org">Litecoin Forum</a></li> <li><a href="http://www.reddit.com/r/litecoin">Reddit Litecoin</a></li> <li><a href="https://twitter.com/search?q=litecoin%20-bitcoin&amp;src=typd">Twitter&#39;da ara</a></li> <li><a href="http://freenode.net/" rel="nofollow">IRC FreeNode</a> IRC kanalları <a href="http://webchat.freenode.net/?channels=litecoin" rel="nofollow">#litecoin</a> (normal kullanıcılar için), <a href="http://webchat.freenode.net/?channels=litecoin-dev" rel="nofollow">#litecoin-dev</a> (geliştiriciler için).</li> </ul>'

      [[Languages.tr.about.row.list]]
        icon = "fa-laptop"
        title = "Kaynaklar"
        description = 'Genel bilgilere, Litecoin&#39;i destekleyen servis ve borsaların listesine <a href="http://litecoin.info">Litecoin Wiki</a>&#39;den ulaşabilirsiniz. <br> Güncel ağ istatistikleri <a href="https://bitinfocharts.com/litecoin">burada</a> yer almaktadır. Litecoin Core ve ilgili projelerin kaynak kodu <a href="https://github.com/litecoin-project">GitHub</a>&#39;da mevcuttur.'

      [[Languages.tr.about.row.list]]
        icon = "fa-heart"
        title = "Özgür ve açık kaynak kodlu yazılım"
        description = "Litecoin, özgür ve açık kaynak kodlu bir yazılımdır ve yazılımı çalıştırmanıza, değiştirmenize, kopyalamanıza ve dağıtmanıza izin veren MIT/X11 lisansı ile yayınlanmaktadır. Yazılım, çalıştırılabilir dosyaların ve karşılığında kodların bağımsız doğrulanmasına izin veren transparan bir süreç ile yayınlanmaktadır."

    [[Languages.tr.about.row]]
      [[Languages.tr.about.row.list]]
        icon = "fa-link"
        title = "Blockchain"
        description = "Litecoin blok zinciri, emsali olan Bitcoin'den çok daha yüksek işlem hacimlerini gerçekleştirebilmektedir. Ağ, daha sık blok oluşturabilmesi nedeniyle, gelecekte yazılımda bir değişikliğe ihtiyaç duymaksızın daha çok işlemi destekler. <br />Bunun sonucunda ticari işletmeler, yüksek etiket fiyatına sahip ürünler sattığında daha fazla onay alma imkanına sahip olurken, daha hızlı onay süreleri elde ederler."

      [[Languages.tr.about.row.list]]
        icon = "fa-lock"
        title = "Cüzdan Şifreleme"
        description = "Cüzdan şifreleme, cüzdanınızı korumanızı sağlar, böylece işlemleri ve hesap bakiyenizi görüntüleyebilirsiniz, ancak litecoin harcamadan önce şifrenizi girmeniz gerekir. <br />Bu, cüzdanınızı çalan virüs ve trojanlara karşı koruma sağlar, bunun yanı sıra ödemeleri göndermeden önce bir sağlık kontrolü yapar."

      [[Languages.tr.about.row.list]]
        icon = "fa-money"
        title = "Madencilik Ödülü"
        description = "Madenciler mevcut olarak blok başına 6.25 yeni litecoin ile ödüllendirilmektedir ve bu miktar yaklaşık olarak her 4 yılda (840,000 blok) bir yarılanmaktadır. <br />Litecoin ağı toplamda 84 milyon litecoin üretmek üzere planlanmıştır ve bu Bitcoin'in 4 katıdır."

  # download section
  [Languages.tr.download]
    enable = true
    gpg = "GPG Signatures"
    download = "İndir"
    source = "Kaynak"
    releasenotes = "Sürüm Notları"
    upgradenotes = "Güncelleme Notları"

    windows = "Windows için"
    mac = "Mac OS X için"
    linux = "Linux için"
    android = "Android için Litewallet"
    electrum = "Electrum Litecoin"

  # Contact section
  [Languages.tr.contact]
    enable = true
    title = "Bizimle iletişime geçin"
    subtitle  = 'Litecoin projesi geliştirme ekibine <a href="mailto:contact@litecoin.org">contact@litecoin.org</a> adresinden ulaşabilirsiniz.'

  # Footer section
  [Languages.tr.footer]
    enable = true
    copyright = 'Telif hakkı &copy; 2011-2023 Litecoin Project. Tüm hakları saklıdır.'
